### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pjotrp** [chfi/purescript-genetics-browser#10]
@chfi I am following instructions as per https://github.com/genenetwork/purescript-genetics-browser/blob/master/README.md (updated).

Missing import or dependency?

```shell
 make build
pulp  --psc-package browserify --skip-entry-point --no-check-main --standalone GGB --main Genetics.Browser.UI  --to ./dist/app.js
* Browserifying project in /gnu/export/local/home/wrk/izip/git/opensource/purescript/genetics-browser
* Building project in /gnu/export/local/home/wrk/izip/git/opensource/purescript/genetics-browser
* Build successful.
* Browserifying...
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'big-integer' from '/gnu/export/local/home/wrk/izip/git/opensource/purescript/genetics-browser/output/Data.BigInt'
    at /gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:170:21)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at DestroyableTransform.emit (events.js:180:13)
    at Readable.<anonymous> (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/browserify-cache-api/lib/proxyEvent.js:3:17)
    at Readable.emit (events.js:180:13)
    at Labeled.<anonymous> (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/read-only-stream/index.js:28:44)
    at Labeled.emit (events.js:180:13)
    at Labeled.<anonymous> (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/stream-splicer/index.js:130:18)
    at Labeled.emit (events.js:180:13)
    at Deps.<anonymous> (/gnu/export/local/home/wrk/.npm-packages/lib/node_modules/pulp/node_modules/stream-splicer/index.js:130:18)
    at Deps.emit (events.js:180:13)
make: *** [Makefile:11: dist/app.js] Error 1
```

**Comment by pjotrp** [comment]
Oh, wait, it may not be able to find the JS libs.

**Comment by pjotrp** [comment]
I think we need something like https://libraries.io/npm/npm-cache-path/dependents. wdyt?

**Comment by pjotrp** [comment]
Needs

```
npm update
+ big-integer@1.6.41
added 1 package and removed 397 packages in 2.475s
```

**Comment by pjotrp** [comment]
success! This was helpful https://qiita.com/kimagure/items/570e6f2bbce5b4724564
